version: '3.8'

services:
  n8n:
    image: n8nio/n8n # <--- CORRIGIDO AQUI! Antes era n8n/n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./data:/home/node/.n8n
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_TLS_REJECT_UNAUTHORIZED=0
      - WEBHOOK_URL=http://${N8N_HOST:-localhost}:5678/
    networks:
      - n8n_network

networks:
  n8n_network:
    driver: bridge